name: Build libjpeg-turbo for Linux x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake nasm build-essential

      - name: Create build directory
        run: mkdir -p build

      - name: Configure build with CMake
        run: |
          cd build
          cmake -G "Unix Makefiles" ..

      - name: Build libjpeg-turbo
        run: |
          cd build
          make -j$(nproc)

      - name: Run tests (optional)
        run: |
          cd build
          make test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: libjpeg-turbo-build
          path: build
