name: Build and Package mozjpeg for Linux x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool nasm pkg-config

      - name: Generate configure script
        run: |
          sh autogen.sh

      - name: Configure build
        run: |
          ./configure --prefix=$GITHUB_WORKSPACE/install

      - name: Build and install mozjpeg
        run: |
          make -j$(nproc)
          make install

      - name: Verify build
        run: |
          install/bin/cjpeg -version

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v3
        with:
          name: mozjpeg-binaries
          path: install/bin
