name: Build MozJPEG for Linux x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake nasm autoconf automake libtool pkg-config
      
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake -G"Unix Makefiles" ..
        make -j$(nproc)
      
    - name: Create package
      run: |
        cd build
        make install DESTDIR=../mozjpeg-install
        cd ..
        tar -czvf mozjpeg-linux-x64.tar.gz mozjpeg-install/
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: mozjpeg-linux-x64
        path: mozjpeg-linux-x64.tar.gz
