name: Build mozjpeg for Linux x64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool nasm pkg-config

      - name: Prepare build system
        run: |
          autoreconf -fiv

      - name: Configure mozjpeg
        run: |
          ./configure

      - name: Build mozjpeg
        run: |
          make -j$(nproc)
