name: Build MozJPEG for Linux x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8  # Using RHEL 8 base image
      
    steps:
    - uses: actions/checkout@v3
      
    - name: Install build dependencies
      run: |
        dnf install -y epel-release
        dnf install -y gcc gcc-c++ make cmake autoconf automake libtool nasm git
        
    - name: Configure and build MozJPEG
      run: |
        mkdir build
        cd build
        cmake -G"Unix Makefiles" \
              -DCMAKE_INSTALL_PREFIX=/usr/local \
              -DCMAKE_BUILD_TYPE=Release \
              ..
        make -j$(nproc)
        
    - name: Create package
      run: |
        cd build
        make install DESTDIR=$PWD/install
        tar -czvf mozjpeg-linux-x64.tar.gz -C install .
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mozjpeg-linux-x64
        path: build/mozjpeg-linux-x64.tar.gz
