name: Build MozJPEG Static Binaries for RHEL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake nasm autoconf automake libtool pkg-config wget unzip
      
    - name: Download and build static zlib (latest version)
      run: |
        # Download latest zlib 1.3.1
        wget https://github.com/madler/zlib/archive/refs/tags/v1.3.1.zip -O zlib.zip
        unzip zlib.zip
        cd zlib-1.3.1
        ./configure --prefix=/tmp/local --static
        make -j$(nproc)
        make install
        cd ..
      
    - name: Download and build static libpng (latest version)
      run: |
        # Download latest libpng 1.6.47
        wget https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.47.zip -O libpng.zip
        unzip libpng.zip
        cd libpng-1.6.47
        autoreconf -fiv
        CPPFLAGS="-I/tmp/local/include" LDFLAGS="-L/tmp/local/lib" ./configure --prefix=/tmp/local --disable-shared --enable-static
        make -j$(nproc)
        make install
        cd ..
        
        # Verify that libpng.a exists and is a valid archive
        ls -la /tmp/local/lib/libpng*.a
        file /tmp/local/lib/libpng*.a
      
    - name: Configure MozJPEG
      run: |
        mkdir -p build
        cd build
        
        # Set environment variables to help CMake find our libraries
        export PKG_CONFIG_PATH=/tmp/local/lib/pkgconfig
        export CMAKE_PREFIX_PATH=/tmp/local
        
        # Configure with static options and explicitly specify PNG paths
        # Note: ENABLE_SHARED=OFF to avoid the PIC issue
        cmake -G"Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_SHARED=OFF \
          -DENABLE_STATIC=ON \
          -DWITH_JPEG8=ON \
          -DPNG_SUPPORTED=ON \
          -DPNG_INCLUDE_DIR=/tmp/local/include \
          -DPNG_LIBRARY=/tmp/local/lib/libpng.a \
          -DZLIB_INCLUDE_DIR=/tmp/local/include \
          -DZLIB_LIBRARY=/tmp/local/lib/libz.a \
          -DCMAKE_INSTALL_PREFIX=/opt/mozjpeg \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          ..
      
    - name: Build MozJPEG
      run: |
        cd build
        make -j$(nproc)
      
    - name: Build static binaries
      run: |
        cd build
        
        echo "Available static libraries:"
        find . -name "*.a" | sort
        
        # List object files in cjpeg and djpeg directories
        echo "Object files in cjpeg:"
        find cjpeg -name "*.o" | sort
        
        echo "Object files in djpeg:"
        find djpeg -name "*.o" | sort
        
        # Compile cjpeg statically
        echo "Building static cjpeg..."
        gcc -static -o cjpeg.static cjpeg/*.o ./*.a /tmp/local/lib/libpng.a /tmp/local/lib/libz.a -lm
        
        # Compile djpeg statically
        echo "Building static djpeg..."
        gcc -static -o djpeg.static djpeg/*.o ./*.a /tmp/local/lib/libpng.a /tmp/local/lib/libz.a -lm
      
    - name: Verify static linking
      run: |
        cd build
        echo "Checking if cjpeg is statically linked:"
        file cjpeg.static
        ldd cjpeg.static || echo "Good! Binary is statically linked."
        
        echo "Checking if djpeg is statically linked:"
        file djpeg.static
        ldd djpeg.static || echo "Good! Binary is statically linked."
      
    - name: Create package
      run: |
        mkdir -p mozjpeg-static/bin
        cp build/cjpeg.static mozjpeg-static/bin/cjpeg
        cp build/djpeg.static mozjpeg-static/bin/djpeg
        tar -czvf mozjpeg-static-rhel.tar.gz mozjpeg-static/
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mozjpeg-static-rhel
        path: mozjpeg-static-rhel.tar.gz
