on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: mozilla/mozjpeg

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake nasm autoconf automake libtool pkg-config wget unzip

    - name: Download and build static zlib
      run: |
        wget https://github.com/madler/zlib/archive/refs/tags/v1.3.1.zip -O zlib.zip
        unzip zlib.zip
        cd zlib-1.3.1
        ./configure --prefix=/tmp/local --static
        make -j$(nproc)
        make install
        cd ..

    - name: Download and build static libpng
      run: |
        wget https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.47.zip -O libpng.zip
        unzip libpng.zip
        cd libpng-1.6.47
        autoreconf -fiv
        CPPFLAGS="-I/tmp/local/include" LDFLAGS="-L/tmp/local/lib" ./configure --prefix=/tmp/local --disable-shared --enable-static
        make -j$(nproc)
        make install
        # Create a symlink so that libpng16.a is available as libpng.a
        cd /tmp/local/lib
        if [ ! -f libpng.a ]; then
          ln -s libpng16.a libpng.a
        fi

    - name: Configure MozJPEG (Static with PNG enabled)
      run: |
        mkdir -p build
        cd build
        # Set up environment variables so CMake can find our libraries via pkg-config
        export PKG_CONFIG_PATH=/tmp/local/lib/pkgconfig
        export CMAKE_PREFIX_PATH=/tmp/local
        cmake -G"Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DWITH_JPEG8=ON \
          -DPNG_SUPPORTED=ON \
          -DCMAKE_INSTALL_PREFIX=/opt/mozjpeg \
          -DCMAKE_C_FLAGS="-fPIC" \
          ..

    - name: Build MozJPEG
      run: |
        cd build
        make -j$(nproc) VERBOSE=1

        # List built files for verification
        echo "=== Built files ==="
        find . -name "*.a" | sort
        find . -type f -executable | sort

    - name: Prepare static binaries
      run: |
        cd build
        if [ ! -f "cjpeg-static" ]; then
          echo "ERROR: cjpeg-static not found!"
          exit 1
        fi
        if [ ! -f "djpeg-static" ]; then
          echo "ERROR: djpeg-static not found!"
          exit 1
        fi
        echo "Static binaries are available."

    - name: Create package
      run: |
        mkdir -p mozjpeg-static/bin
        cp build/cjpeg-static mozjpeg-static/bin/cjpeg
        cp build/djpeg-static mozjpeg-static/bin/djpeg

        # Verify the binaries
        file mozjpeg-static/bin/cjpeg
        file mozjpeg-static/bin/djpeg

        tar -czvf mozjpeg-static-rhel.tar.gz mozjpeg-static/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mozjpeg-static-rhel
        path: mozjpeg-static-rhel.tar.gz
